[team-websites]
team.a.url = "https://tarheels.live/teama/"
team.b.url = "https://tarheels.live/comp523teamb2023/"
team.c.url = "https://tarheels.live/523groupc/"
team.d.url = "https://tarheels.live/comp523teamd/"
team.e.url = "https://tarheels.live/comp523teame2023"
team.f.url = "https://tarheels.live/sp23comp523teamf/"
team.g.url = "https://tarheels.live/comp523groupg/"
team.h.url = "https://tarheels.live/comp523sp23teamh"
team.i.url = "https://tarheels.live/teami523/"
team.j.url = "https://tarheels.live/teamj/"
team.k.url = "https://tarheels.live/comp523teamk2023/"
team.l.url = "https://tarheels.live/comp523s23teaml/"
team.m.url = "https://tarheels.live/teamm/"
team.n.url = "https://tarheels.live/comp523groupn/"
team.o.url = "https://tarheels.live/comp523teamo/"
